### ISSUE TITLE
HLS: autoPlay doesn't work when there's jQuery instance on the page

### ISSUE THREAD

**Issue by konashark** [globocom/clappr#323] opened 2015-01-07 20:56 UTC
I've been happily using 0.51 version of Clappr to play my .m3u8 streams and tried updating to a newer release. After trying 10 of them I determined that I can't get any version of the player from .65 on to play in Chrome (latest version 39). I suspect it's related to the above change, but I do not know:

HTML5Video.canPlay = function(resource) {
  if (Browser.isSafari || Browser.isMobile || Browser.isWin8App || Browser.isLegacyIE) {
    return true;
  } else if (Browser.isChrome || Browser.isFirefox || Browser.isIE) {
    return (!!resource.match(/(.*).(mp4|webm)/));
  }
};

I tried forcing the response to 'true' (as it was before) or add "m3u8" (my stream type) to the matcher, all I get are the pulsing dots and no video.

Any ideas?

**Comment by flavioribeiro** [comment] 2015-01-07 20:57
hey @konashark can you provide your source url?

**Comment by flavioribeiro** [comment] 2015-01-07 21:01
Also, if you're compiling from scratch, I would suggest you to try playing your stream on  http://cdn.clappr.io. If it works, your workspace is dirty of old dependencies (we changed a _lot_ of them during this time range).

**Comment by konashark** [comment] 2015-01-07 21:42
I haven't been compiling anything - I was just taking the clappr.js and clappr.map files from the 'dist' folder of the releases. Am I missing some critical step that I should know?
I can't give you my url directly as it is inside a corporate network, but happily, I see that if I plug the url into the cdn.clappr.io page under the same browser, it plays there! I will need to continue experimenting, but so far it has been 100% reproducible, drop in the files from .64 and it plays, drop in the files from .65 or beyond and it doesn't. (And by the way - a big Thanks to you guys for taking on such an incredibly useful project!)

**Comment by flavioribeiro** [comment] 2015-01-07 21:47
sure @konashark you can send me directly on email@flavioribeiro.com

**Comment by flavioribeiro** [comment] 2015-01-08 01:15
hey @konashark I think we introduced a bug when setting width/height as percentage. Version `0.0.83` fix this, I could play the video using the parameters you provided me in private. Here is the full code of my jeff.html :)

```html
<html>
  <head>
    <script type="text/javascript" src="http://cdn.clappr.io/latest/clappr.min.js"></script>
  </head>
  <body>
  <div id="player"></div>
  <script>
    window.onload = function() {
      var player = new Clappr.Player({
        source: "http://cdn.bem.tv/stream/soccer5/playlist.m3u8", 
        parentId: "#player",
        flushLiveURLCache: false,
        autoPlay: true,
        width: "100%",
        height: "100%"
      });
    }
  </script>
  </body>
</html>
```

Make sure that you're loading version 0.0.83 of the player (by typing Clappr.version on your console). Tell me if it works for you and if so, please consider close this issue, ok?

**Comment by flavioribeiro** [comment] 2015-01-08 19:54
Hey @konashark can you please try to play this url and tell me if works? http://flv.io/jeff.html

**Comment by flavioribeiro** [comment] 2015-01-09 13:27
@konashark latest version of clappr doesn't support width/height as percentage anymore. I suggest you to use `window.innerWidth` and `window.innerHeight` instead of 100%

**Comment by flavioribeiro** [comment] 2015-01-15 17:43
hi @konashark any update on this? I couldn't reproduce it by adding jquery-2.1.1 in the same page that the player is embedded on.

**Comment by konashark** [comment] 2015-01-15 23:09
Hi!
I temporarily had to move on, but in response to your question I set up an
Apache server on my wife's MacMini and tried the same test code (Mac
Yosemite + Chrome 39) there to see if it behaved any differently.

Exactly the same results as on my work laptop: m3u8 plays automatically if
no jQuery. With jQuery, it won't auto start, but clicking the play icon
starts it playing. Works fine under Safari. MP4 auto plays with or without
jQuery.

If I don't use a web server, then it won't play m3u8 at all... presumably
some cross domain issue or something.

-Jeff

**Comment by flavioribeiro** [comment] 2015-01-17 19:29
Hey,

Yes, if you don't use a web server, no flash components will work. So, let's check if I understood. The scenario is: auto play doesn't work for latest clappr trying to play m3u8 source on chrome 39 with jquery embedded on the same page. Am I right?

**Comment by konashark** [comment] 2015-01-21 05:43
Yes. All tests on a Mac.

**Comment by flavioribeiro** [comment] 2015-01-21 13:09
great @konashark, I could reproduce here. I'll try to fix right now.

**Closed** 2015-01-21 16:20 UTC
Labels: bug

**Comment by flavioribeiro** [comment] 2015-01-21 16:21
it should be fixed now. Please note that we do not support percentage on width/height anymore, so I suggest you to use `window.innerWidth` and `window.innerHeight` instead of 100%. We're going to bump a new version in a few hours. Thank you for all the support and patience!

**Comment by konashark** [comment] 2015-01-22 00:06
Horray!
I grabbed the latest version and now I see the .m3u8 autoplay in Chrome 
+ jQuery on the Mac.
I'm glad you found it... thanks for your help, and I'm glad I'm not crazy.

-Jeff
