### ISSUE TITLE
RTMP Stream documentation

### ISSUE THREAD

**Issue by aggietallboy** [globocom/clappr#286] opened 2014-12-17 15:19 UTC
Good morning and thank you for making this available!

I am trying to build an internal stream server using Ubuntu and nginx. So far the stream server works well, but I'm having challenges with also basing the player on this machine.

I've made a simple player.html file based on the example in the readme.md

```
<head>
  <script type="text/javascript" src="http://cdn.clappr.io/latest/clappr.min.js$
</head>
<body>
  <div id="player"></div>
  <script>
    var player = new Clappr.Player({
        source: "rtmp://10.1.1.20/live",
        parentId: "#player"
        });
  </script>
</body>
```

To publish the rtmp stream I use a key - let's say 'xyzxyz'

I can validate the stream using [Wowza's player](http://www.wowza.com/resources/3.5.0/examples/LiveVideoStreaming/FlashRTMPPlayer/player.html) but I'm not clear on the correct syntax to use here to specify the stream key/name.

Thanks!

Roger

**Comment by aggietallboy** [comment] 2015-01-05 18:09
Latest update is that it was not working with x264, but not Clappr.

As of this moment though Quick Sync encoding, with all other defaults is working on my one machine... will start testing other machines again.

**Comment by kyleparisi** [comment] 2015-01-06 03:09
@flavioribeiro Just let me know a day you'll be working on it and I can turn my server on if you want so you can stream, otherwise I can stream my static desktop....

I'm still suspicious of that LoaderInfo.  I played with it a little longer after posting and none of the functions seemed to be bound to the html object.  Once I commented out the LoaderInfo, they were there.  I didn't get any further because the player API seemed a little difficult to build up the player.  I think it would be wise to fork it out [If that's what you meant].

**Comment by flavioribeiro** [comment] 2015-01-07 17:01
Hey guys, I just released a first version of [clappr-rtmp-plugin](https://github.com/flavioribeiro/clappr-rtmp-plugin) which has initial support for both VoD and live videos.

It's possible to test with your source by adding the external plugin on player embed:

```javascript
<script type="text/javascript" src="http://cdn.jsdelivr.net/clappr.rtmp/0.0.2/rtmp.min.js">
</script>
```
and 
```javascript
var player = new Clappr.Player({
    source: "rtmp://source_here", 
    parentId: "#player-wrapper", 
    plugins: {'playback': [RTMP]});
```
Tell me if works for you. It's possible to see it in action on [clappr-mosaic](http://flavioribeiro.github.io/clappr-mosaic/).

I'm differentiating live/vod streams by search on the word `live` inside RTMP source URL. Do you guys have a better idea?

**Comment by kyleparisi** [comment] 2015-01-08 01:04
I confirmed it is working.

One other idea might be looking for the file extensions that you support which might get dicey.  It looks like some other players have a file option or they use a prefix in the source.

**Comment by flavioribeiro** [comment] 2015-01-08 01:18
great! I'll wait for @aggietallboy before close this. Thank you :+1:

**Comment by aggietallboy** [comment] 2015-01-08 17:33
I'm afraid I've just got a blank page:


<html><head><title>Clappr Player</title><script type="text/javascript" src="
http://cdn.jsdelivr.net/clappr.rtmp/0.0.2/rtmp.min.js"></script>

<body> <div id="player"></div> <script> var player = new Clappr.Player({
source: "rtmp://myfeedurl", height: 768, width: 1024, autoPlay: true, mute:
true, parentId: "#player", plugins: {'playback': [RTMP]} }); </script>
</body>
</html>

**Comment by flavioribeiro** [comment] 2015-01-08 17:50
You need to add Clappr player also. Here is the full html:
https://gist.github.com/e6bb189cf903aabe5d52


*Flávio Ribeiro *
*(flv.io <http://flv.io> | blog <http://flavioribeiro.com>)*

**Comment by aggietallboy** [comment] 2015-01-08 20:08
well that makes sense :)

**Comment by aggietallboy** [comment] 2015-01-08 20:15
so far so good... working in Chrome and IE for me and a few other users here

**Comment by flavioribeiro** [comment] 2015-01-08 20:18
awesome! I just got a small bug on IE10 where the video is not using the full player box, but I'll close this issue for now. Please open any bug/feature/issue related to RTMP on https://github.com/flavioribeiro/clappr-rtmp-plugin ok? thank you guys!

**Closed by flavioribeiro** 2015-01-08 20:18 UTC
Labels: bug, question

**Comment by aggietallboy** [comment] 2015-01-08 20:45
multiple internal users can now see it (awesome!)

Whether specifying height/width or not, it seems that IE renders a  limited
view onto the stream, where chrome gets the whole thing


I'll PM you some screen shots.


Another challenge -- opening the page from the outside world doesn't
display the stream (which is actually perfect in my scenario) -- the stream
goes to a private IP... so when i pull up the page from outside, at the
link I gave you in PM, it won't load anything.
